#!/bin/bash
# Builds a standalone Sill.app at build/Sill.app.
set -euo pipefail
cd "$(dirname "$0")/.."

swift build -c release

APP=build/Sill.app
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp .build/release/Sill "$APP/Contents/MacOS/Sill"
cp Scripts/Info.plist "$APP/Contents/Info.plist"

# The zsh integration ships inside the bundle; onboarding sources it from
# here, so its path must survive app updates (it does — Resources is stable).
cp ShellIntegration/sill.zsh "$APP/Contents/Resources/sill.zsh"
# Localizations: SwiftPM packs the .lproj string tables into a resource
# bundle; Localization.swift looks for it here (never via Bundle.module).
cp -R .build/release/Sill_Sill.bundle "$APP/Contents/Resources/"

# Embed Sparkle.framework (auto-update). The binary references it via
# @rpath/../Frameworks (see Package.swift linkerSettings).
SPARKLE=$(find .build/artifacts -type d -name Sparkle.framework -path "*macos*" | head -1)
mkdir -p "$APP/Contents/Frameworks"
cp -R "$SPARKLE" "$APP/Contents/Frameworks/"

# Compile the Icon Composer document (Assets/AppIcon.icon, generated by
# Scripts/make-assets.swift) into Assets.car — on macOS 26+ the system
# renders the icon's Liquid Glass appearance live, including the dark/clear/
# tinted variants — plus a fallback AppIcon.icns rendered from the layers.
if [[ -d Assets/AppIcon.icon ]]; then
    ICONBUILD=$(mktemp -d)
    # Absolute path on purpose: actool delegates to the ibtoold daemon,
    # which caches compilations keyed by the document path as passed —
    # sibling apps all saying "Assets/AppIcon.icon" collide and get each
    # other's icons.
    xcrun actool "$PWD/Assets/AppIcon.icon" --compile "$ICONBUILD" \
        --platform macosx --minimum-deployment-target 26.0 \
        --app-icon AppIcon --output-partial-info-plist "$ICONBUILD/partial.plist" \
        --output-format human-readable-text --errors > /dev/null
    cp "$ICONBUILD/Assets.car" "$APP/Contents/Resources/Assets.car"
    cp "$ICONBUILD/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"
    rm -rf "$ICONBUILD"
    /usr/libexec/PlistBuddy -c "Add :CFBundleIconFile string AppIcon" "$APP/Contents/Info.plist"
    /usr/libexec/PlistBuddy -c "Add :CFBundleIconName string AppIcon" "$APP/Contents/Info.plist"
fi

# With CODESIGN_IDENTITY set (e.g. "Developer ID Application"), produce a
# distributable, notarization-ready signature (hardened runtime + timestamp).
# Otherwise fall back to ad-hoc, which is fine locally — but note TCC ties
# the Accessibility grant to the signature, so ad-hoc rebuilds re-prompt.
if [[ -n "${CODESIGN_IDENTITY:-}" ]]; then
    SIGN=(codesign --force --options runtime --timestamp --sign "$CODESIGN_IDENTITY")
else
    SIGN=(codesign --force --options runtime --sign -)
fi

# Sparkle's helpers must be signed individually, innermost first
# (https://sparkle-project.org/documentation/sandboxing/#code-signing).
FW="$APP/Contents/Frameworks/Sparkle.framework"
"${SIGN[@]}" --preserve-metadata=entitlements "$FW/Versions/B/XPCServices/Downloader.xpc"
"${SIGN[@]}" "$FW/Versions/B/XPCServices/Installer.xpc"
"${SIGN[@]}" "$FW/Versions/B/Autoupdate"
"${SIGN[@]}" "$FW/Versions/B/Updater.app"
"${SIGN[@]}" "$FW"
"${SIGN[@]}" "$APP"

echo "Built $APP"
echo "Run:  open $APP"
